# Generated by Django 4.2 on 2024-08-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_extendeduser_created_time_extendeduser_modified_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveBigIntegerField(verbose_name='phone number')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip address')),
                ('block_until', models.DateTimeField(verbose_name='block until')),
            ],
            options={
                'verbose_name': 'block',
                'verbose_name_plural': 'blocks',
            },
        ),
    ]
