# Generated by Django 4.2 on 2024-08-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, unique=True, verbose_name='ip address'),
        ),
        migrations.AlterField(
            model_name='block',
            name='phone_number',
            field=models.PositiveBigIntegerField(null=True, unique=True, verbose_name='phone number'),
        ),
    ]
