# Generated by Django 4.2 on 2024-08-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_block_ip_address_alter_block_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='ip address'),
        ),
        migrations.AlterField(
            model_name='block',
            name='phone_number',
            field=models.PositiveBigIntegerField(null=True, verbose_name='phone number'),
        ),
    ]
